version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
      # environment variables for all commands executed in the primary container
        environment:
          GIT_AUTHOR_NAME: circleci
          GIT_AUTHOR_EMAIL: noreply@circleci.com
          GIT_COMMITTER_NAME: circleci
          GIT_COMMITTER_EMAIL: noreply@circleci.com
          EMAIL: noreply@circleci.com

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx2048m
      TERM: dumb

    steps:
      - add-ssh-keys:
         fingerprints:
           - "a8:81:20:53:dc:53:da:0f:60:c2:31:32:3c:ff:a1:a8"
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew clean test bumpVersion

      - store_artifacts:
          path: build/reports
          destination: reports

      - deploy:
          name: deploy to bintray
          command: |
            if [ "$CIRCLE_BRANCH" == "alpha" ] || [ "$CIRCLE_BRANCH" == "beta" ] || [ "$CIRCLE_BRANCH" == "master" ]; then
              ./gradlew release -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_API_KEY -PawsMavenAccessKey=$AWS_ACCESS_KEY_ID -PawsMavenSecretKey=$AWS_SECRET_KEY
            elif [ "$CIRCLE_BRANCH" == "integration" ]; then
              ./gradlew publishMavenS3PublicationToSnapshotRepository -PawsMavenAccessKey=$AWS_ACCESS_KEY_ID -PawsMavenSecretKey=$AWS_SECRET_KEY
            fi
